### ISSUE TITLE
When using a class with potions, players can effect each other in lobby

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#29]
When players are in a game lobby waiting for a game to start, if their class has potions, they can throw potions at other players. While they won't actually affect the player, once the game starts, any remaining potion effects will still be active once the game starts.

**Comment by ghost** [comment]
Yes, that happened. I was still in the game lobby when it happened.

**Comment by dellman135** [comment]
This issue has been fixed.

**Comment by justwheel** [comment]
I think @dellman135 meant to comment on here to confirm this issue. It's still an issue with the latest commit. Although this can be resolved with a plugin like WorldGuard, the plugin should prevent the usage and dropping of items such as potions before the game starts.

**Comment by justwheel** [comment]
Confirmed fixed. It also will start the player off with the correct number of items, even if it "appears" they used them all (as expected). :+1:
